apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: ghcr.io/94manuel/gelato-api
  newName: ghcr.io/94manuel/gelato-api
  newTag: sha-01339c4
- name: ghcr.io/94manuel/gelato-web
  newName: ghcr.io/94manuel/gelato-web
  newTag: sha-01339c4
