apiVersion: batch/v1
kind: Job
metadata:
  name: gelato-api-migrate
  namespace: gelato
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        app: gelato-api-migrate
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: ghcr-secret
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: migrate
          image: ghcr.io/94manuel/gelato-api:main
          imagePullPolicy: Always
          command:
            - sh
            - -c
            - npx prisma migrate deploy --schema apps/api/prisma/schema.prisma
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: gelato-postgres-secret
                  key: DATABASE_URL
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 384Mi
